- name: Playbook to update Windows 10 gold image for Horizon 7
  hosts: localhost
  gather_facts: no
  vars_files:
    - pb-vars.yaml
    
  tasks:
  
  - name: Power on VM
    vmware_guest:
      hostname: "{{ vcenter_server }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ vcenter_datacenter }}"
      validate_certs: no
      name: "{{ template_name }}"
      state: poweredon
      wait_for_ip_address: yes
    when: template_name is defined
    register: vm_out

  - name: Paws
    pause:
      seconds: 10
  
  - name: Add the host
    add_host:
      name: "{{ vm_out.instance.hw_name }}"
      ansible_connection: winrm
      ansible_port: 5986
      ansible_host: "{{ vm_out.instance.ipv4 }}"
      ansible_user: "{{ windows_user }}"
      ansible_password: "{{ windows_user_pass }}"
    no_log: true


  
  - name: Run all security and critical updates
    win_updates:
      reboot: yes
      reboot_timeout: 2400
      category_name:
        - SecurityUpdates
        - CriticalUpdates
        - UpdateRollups
