---
- name: Install Apache
  hosts: centos
  become: true

  vars_files:
    - vars/apache_default.yml
    - vars/apache_{{ ansible_os_family }}.yml

  handlers:
    - name: restart apache
      service:
        name: "{{ apache_service }}"
        state: restarted

  tasks:
    
    - name: Ensure Apache is installed
      package:
        name: "{{ apache_package }}"
        state: present

    - name: Copy test config file.
      copy:
        src: test.conf
        dest: "{{ apache_config_dir }}/test.conf"
      notify: restart apache    

    - name: Make sure apache is started now & at boot
      service:
        name: httpd
        state: started
        enabled: true